version: '1.0'

services:
  app-db-service:
    container_name: app-db-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}  # Set database credentials
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"  # Map port 5432 of the host to port 5432 of the postgres container
    volumes:
      - app-data:/var/lib/postgresql/data  # Persist database data

  pgadmin-service:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    ports:
      - "5050:80"  # Map port 5050 of the host to port 80 of the pgadmin container
    environment:
      PGADMIN_DEFAULT_EMAIL: xyz@abc.com  # Set pgAdmin login credentials
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped
    depends_on:
      - app-db-service  # Wait for postgres database to be ready before starting pgAdmin


  main-backend-service:
    container_name: backend-container
    build: ./main-backend
    depends_on:
      - app-db-service  # Wait for postgres database to be ready before starting app
    ports:
      - "8080:3000"  # Map port 8000 of the container to port 8000 of the host
    env_file:
      - ./main-backend/.env  # Load environment variables from .env file


volumes:
  app-data:  # Persistent storage for postgres data